#!/usr/bin/env bash
# Script Bash que configura una nueva máquina Ubuntu para
# respetar los requisitos anteriores
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R ubuntu /var/www
echo "Hello World" > /var/www/html/index.nginx-debian.html
service nginx start
