#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

i=0
h=0
m=0
while [ $i -le 779 ]
do
    if(( i % 60 == 0 ))
    then
      echo "Hour: $h"
      m=0
      ((h++))
    else
      echo "$m"
    fi
    ((i++))
    ((m++))
done

